### ISSUE TITLE
[1.12.2] the mod is considered a trojan by windows defender

### ISSUE THREAD

**Issue by Biviho** [flowerinsnowdh/GreatScrollableTooltips#15]
hi! i'm getting a notification about the mod being a trojan from windows defender, this is new

the type of threat : Trojan:Script/Wacatac.B!ml
file: D:\Videogames\Games\giochi\Minecraft\MultiMC\instances\Riftwalker's Tales\.minecraft\mods\great-scrollable-tooltips-4.1.2.jar

**Comment by flowerinsnowdh** [comment]
你好！建议您不要忽略这个警告。

请问你是从哪里下载到该 Mod 的？modrinth？CurseForge？还是GitHub releases？

如果可以，请将该副本发送到这里或我的邮箱 flowerimsnow@gmail.com

<hr />

Hello! It is recommended that you do NOT ignore this warning.

Where did you download this Mod from? modrinth? CurseForge? Or GitHub releases?

If possible, please send a copy of it to here or to my email address flowerimsnow@gmail.com

**Comment by Biviho** [comment]
Hi! I deleted it immediately, it was from curseforge, the latest 1.12 relase

When iget to the computer i will send you a copy

**Comment by Biviho** [comment]
i can't sent it via email since it's considered potentially harmful, i'll attatch the link to the cursefrge download here, i can't even attatch the file cause i can't zip it since it's considered harmful, and git does not support jar:

[the link](https://www.curseforge.com/minecraft/mc-mods/great-scrollable-tooltips/files/5158773)

**Comment by flowerinsnowdh** [comment]
如果那样，我觉得这可能是一个错误，我会向微软反馈的

感谢您的反馈！

<hr />

If that, this might be a error and I'll report it to Microsoft.

Thanks for your feedback!

**Comment by flowerinsnowdh** [comment]
如果那样，我觉得这可能是一个错误，我会向微软反馈的

在那之前，您可以添加排除项来避免错误的通知。

感谢您的反馈！

<hr />

If that, this might be a error and I'll report it to Microsoft.

Until then, you can add exclusions to avoid false notifications.

Thanks for your feedback!

**Comment by Biviho** [comment]
it looks like the version 4.2.0 alpha 1 does not have this issue
