### ISSUE TITLE
Forge Version Crashes with OptiFine

### ISSUE THREAD

**Issue by DumbXBoxAcct** [flowerinsnowdh/GreatScrollableTooltips#55]
Let me start by saying how much this mod has helped me out in Fabric, it's awesome!  When I saw the Forge version, I was ecstatic because I hoped to actually be able read lengthy tooltips in Forge, at last, without having to re-size my screen.

Unfortunately, though, when I run MC 1.20.1, with Forge 47.3.0 and the .jar for Optifine 1.20.1_HD_U_I6 in "mods", along with the latest version of Great Scrollable Tooltips for Forge (15.1.0) and - literally - NO other mods and NO resource packs, the game crashes on startup.  I'm also NOT using any sort of shader with the game.  

I've included the "latest.log" and "debug.log" files here, in case they're at all helpful.

I should also mention that I tried running the game WITHOUT OptiFine, with GSTT as the ONLY mod loaded and the game started up just fine.

Hoping that, if you can duplicate this, it's possible to fix because I'm dying to get GSTT running on Forge!

[latest.log](https://github.com/user-attachments/files/16185718/latest.log)

[debug.log](https://github.com/user-attachments/files/16185720/debug.log)

**Comment by flowerinsnowdh** [comment]
Hello! Thanks for your support! When I hear you say loving this mod, and it helped you a lot, I am ecstatic.

But it's a pity, I can make it compatible with any open source mod, but Optifine is a closed source mod, and I don't know the implementation method of Optifine. The log files also don't give me enough useful information. Sorry I am unable to make it compatible.

Maybe try other mods insted Optifine? Like [Iris](https://github.com/IrisShaders/Iris) [Capes](https://github.com/CaelTheColher/Capes) (Zoomify)[https://github.com/isXander/Zoomify]

I know not all of them support forge, but please allow me to apologize again. I really don't know how to make it compatible with Optifine

Terribly sorry.

I will close the current issue first. If you have any questions, please reopen and continue to reply.
