### ISSUE TITLE
与神化不兼容

### ISSUE THREAD

**Issue by NaClSolution** [flowerinsnowdh/GreatScrollableTooltips#60]
与神化模组不兼容，当物品镶嵌宝石时，移动提示框宝石不会动,而且在重铸台界面也无法使用。
![2024-07-22_21 57 40](https://github.com/user-attachments/assets/9d5c2aed-17fb-4258-b3a5-227459b7827f)

**Comment by flowerinsnowdh** [comment]
您好，抱歉，我不熟悉此 Mod，麻烦您描述一下此问题的复现方法，谢谢

以及能否放出该 Mod 的相关链接或者 GitHub 仓库？

**Comment by flowerinsnowdh** [comment]
Closed due to long period of no information.

If you have more problem, please reopen this issue.
