### ISSUE TITLE
[Bug] Bundles aren't working correctly

### ISSUE THREAD

**Issue by Czekoloczek** [flowerinsnowdh/GreatScrollableTooltips#87]
The scrolling feature for bundles isn't working correctly.

"Scrolling on bundles in an inventory allows for scrolling through the bundle's slots, which starts off as the most recently added slot, and is displayed with a bright underlay behind that slot. During this process, the bundle's icon will appear open, and the selected slot's item icon will appear within the bundle's icon, though this is not shown in the player's hand."

**Comment by flowerinsnowdh** [comment]
I understand this problem. But I can't understand the "player's hand". You mean the **cursor**, right?

**Comment by Czekoloczek** [comment]
It was just copy pasted from the mincraft wiki, so you know which feature I was talking about since it was new at the time of creating this issue
also i made a recording of the issue


### With the mod:

https://github.com/user-attachments/assets/62f2566f-27f2-4a43-a53a-51a5dae35bcc

### Without the mod:

https://github.com/user-attachments/assets/2f78a9b5-31af-4d0e-a59f-27d7a2350bde

(about the player's hand part (not important): as you can see in the recording above the items show in the bundle in the inventory and the hotbar but not the player's hand)

**Comment by flowerinsnowdh** [comment]
Sorry for my poor comprehension. Until I launch my game, I thought you mean the

> not shown in the player's hand

is the issue you want to describe.

Thank you. Issue solved on [v16.2.0-beta.1+fabric](https://github.com/flowerinsnowdh/GreatScrollableTooltips/releases/tag/v16.2.0-beta.1%2Bfabric)
